# fly.toml app configuration file generated for e-commerce-course-api on 2024-11-17T00:00:19-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'e-commerce-course-api'
primary_region = 'scl'

[build]
  image = 'jorgeriveramancilla/e-commerce-course-api:latest'

[env]
  ASPNETCORE_URLS = 'http://+:8080'
  Cloudinary__ApiKey = '526587737374245'
  Cloudinary__CloudName = 'di06rv0hj'
  StripeSettings__PublishableKey = 'pk_test_51PrPxiH6vGETLfN35pfU32vue1Ir7VepGeuicC3BZBTshpjx4KprTjDwbG3ftjWdC5kgvL9wBG8QBTYn58tb0I7N00juOXGghn'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
